### ISSUE TITLE
Reference to getResourceFacade() method in comment

### ISSUE THREAD

**Issue by igorgallingani** [moqui/moqui-kie#1]
At line 147, file KieToolFactory.groovy, there is a reference to getResourceFacade() method in comment.  

String drl = sc.compile(getResourceFacade().getLocationStream("component://mantle-usl/kie/src/main/resources/mantle/shipment/orderrate/OrderShippingDt.xls"), InputType.XLS)

**Comment by jonesde** [comment]
What is the issue? Better to get rid of that old commented code? Done in commit #dd77bf7.

**Comment by igorgallingani** [comment]
😅
